Reef admins
aqualinkorg/aqualink-app pull request #128
Opened 2020-09-04 13:34 UTC by avalmas-programize

- Add `reef-to-admin` table (custom intermediate table for manyToMany relationship between admin and reef)
- Change reef \ admin relationship from manyToOne (users can have many reefs but a reef has only one admin) to manyToMany (reefs now can have more than one admin)
- Refactor reef endpoints to follow the manyToMany relationship between user and reef
- Add IsReefAdminGuard to restrict access to reef_managers to only their reefs
- Refactor surveys endpoints:
  - Change survey's global prefix to `reefs/:reef_id/surveys` so that we always track the reef_id, which is needed for IsReefAdminGuard
  - Change GET /surveys/reefs/:id to /reefs/:reef_id/surveys
  - Make necessary changes in the DTOs and survey service

Related issue: https://github.com/aqualinkorg/aqualink-app/issues/111

2020-09-04 14:12 UTC, ericboucher commented on packages/api/src/users/users.service.ts
> +        return this.reefToAdminRepository.save(reefToAdmin);
I think you can just do:

this.reefToAdminRepository.save({adminId: user.id, reefId: reefAssociation.reef.id})

2020-09-04 14:14 UTC, ericboucher commented on packages/api/src/users/users.service.ts
> +    @InjectRepository(ReefToAdmin)
Let's add an endpoint to return the list of reefs administered by the current logged in user

2020-09-04 14:16 UTC, ericboucher commented on packages/api/src/reefs/reef-to-admin.entity.ts
> +  @ManyToOne(() => Reef, (reef) => reef.reefToAdmin, { cascade: true })
Is it safe to have a cascade true here? Doesn't that mean that we would delete the reef if we delete this relationship?

2020-09-04 14:17 UTC, ericboucher commented
@avalmas-programize can you list the necessary frontend changes? Or even have a stab at them? They shouldn't be too complicated at the moment.

2020-09-04 14:20 UTC, ericboucher commented on packages/api/migration/1599209835916-AddReefToAdminTable.ts
> +        CONSTRAINT "PK_481618ed9eb45a5765dd8710596" PRIMARY KEY ("reef_to_admin_id")
We should probably limit duplicates of reef_id, admin_id?

2020-09-04 14:22 UTC, ericboucher commented on packages/api/src/reefs/reefs.controller.ts
> -  @Get(':id/surveys/:poi')
is this not needed anymore?

2020-09-04 14:29 UTC, avalmas-programize commented on packages/api/src/users/users.service.ts
> +        return this.reefToAdminRepository.save(reefToAdmin);
Yes indeed. I forgot about this syntax.

2020-09-04 14:31 UTC, avalmas-programize commented on packages/api/src/reefs/reef-to-admin.entity.ts
> +  @ManyToOne(() => Reef, (reef) => reef.reefToAdmin, { cascade: true })
No. Cascade means that when the Reef is deleted the relationship is deleted also. (the same goes for users)

2020-09-04 14:36 UTC, avalmas-programize commented on packages/api/src/reefs/reefs.controller.ts
> -  @Get(':id/surveys/:poi')
As I see it, this endpoint was using a mock response which is already implemented in the survey details endpoint (GET /reefs/:reef_id/surveys/:id). The only difference was that I fetch all POIs of a survey and this was designed to fetch only one POI of a survey. I don't see any use for it anymore.
Also it was conflicting with the new endpoints (surveys endpoints with the updated prefix)

2020-09-04 14:37 UTC, avalmas-programize commented on packages/api/migration/1599209835916-AddReefToAdminTable.ts
> +        CONSTRAINT "PK_481618ed9eb45a5765dd8710596" PRIMARY KEY ("reef_to_admin_id")
I will add a unique key and some checks when the relation is created to prevent any duplicates.

2020-09-04 14:50 UTC, avalmas-programize commented
Front-end changes:
All `surveys/` endpoints URLs should changes:
- POST /surveys/                                => POST /reefs/:reef_id/surveys/
- POST /surveys/:survey_id/media/    => POST /reefs/:reef_id/surveys/:survey_id/media/
- POST /surveys/upload/                     => POST /reefs/:reef_id/surveys/upload/
- GET /surveys/reefs/:reef_id              => GET /reefs/:reef_id/surveys/
- GET /surveys/:survey_id/                  => GET /reefs/:reef_id/surveys/:survey_id/
- GET /surveys/:survey_id/media/       => GET /reefs/:reef_id/surveys/:survey_id/media/
- PUT /surveys/:survey_id/                  => PUT /reefs/:reef_id/surveys/:survey_id/
- PUT /surveys/media/:media_id/        => PUT /reefs/:reef_id/surveys/:survey_id/
- DELETE /surveys/:survey_id/           => PUT /reefs/:reef_id/surveys/:survey_id/
- DELETE /surveys/media/:media_id/ => PUT /reefs/:reef_id/surveys/:survey_id/

2020-09-04 21:45 UTC, bencpeters commented on packages/api/migration/1599209835916-AddReefToAdminTable.ts
> +        CONSTRAINT "PK_481618ed9eb45a5765dd8710596" PRIMARY KEY ("reef_to_admin_id")
@avalmas-programize A better approach would be to make the primary key itself `(reef_id, admin_id)`

2020-09-04 22:14 UTC, bencpeters requested changes
Some suggested clean-ups throughout, but the big thing is re-doing the schema & entities a bit...

2020-09-04 22:14 UTC, bencpeters commented on packages/api/src/reefs/reef-to-admin.entity.ts
> +export class ReefToAdmin {
You shouldn't need to define a TypeORM entity at all for a join table unless you're trying to store custom information on the join table (e.g. an attribute that describes a condition on the join). In this case you're just trying to set up a many-to-many join between two entities, so defining it in this way has numerous disadvantages:

- This is a class based entity that TypeORM will actually try to instantiate if you load records in some cases, increasing the overhead.
- You have a completely extraneous extra column (`reefToAdminId`) that conveys no extra information and requires a hacky `unique` constraint (the "right" way to set up a table like this would just use the `reefId, adminId` as the primary key.
- This entity forces you to specify a naming convention (which in this case you didn't use the "standard" SQL naming convention for join tables across most web frameworks which would be `reefs_admins`) rather than relying on predictable & standard defaults.

See the [docs on Many-To-Many in TypeORM](https://typeorm.io/#/many-to-many-relations).

This is what you want to do:

```typescript
class Reef {
  // Other attributes
  @ManyToMany(() => User, (user) => user.administered_reefs)
  @JoinTable()
  admins: User[]
}

class User {
  // Other attributes
  @ManyToMany(() => Reef, (reef) => reef.admins)
  administered_reefs: Reef[]
}
```

2020-09-04 22:14 UTC, bencpeters commented on packages/api/src/auth/is-reef-admin.guard.ts
> +      const isReefAdmin = await this.reefToAdminRepository.findOne({
We have an `adminLevel` that corresponds to a reef manager, do we want to enforce that that admin level is set as well?

2020-09-04 22:14 UTC, bencpeters commented on packages/api/src/reefs/reefs.entity.ts
> +import { ReefToAdmin } from './reef-to-admin.entity';
`import type { ReefToAdmin }` (the other no cycle imports should use this as well - get rid of all the linter disable comments)

2020-09-04 22:14 UTC, bencpeters commented on packages/api/src/surveys/surveys.controller.ts
> +  @UseGuards(IsReefAdminGuard)
Rather than requiring us to specify this guard on every single handler, it might be worth adding a `@Public` decorator that does `setMetadata("isPublic", true)` and then look up the metadata on the handler inside the `isReefAdminGuard` function and only lets the request through without the check if that metadata is set. Then you could specify the guard on a controller-wise level here.

2020-09-04 22:14 UTC, bencpeters commented on packages/api/src/surveys/surveys.entity.ts
> +// eslint-disable-next-line import/no-cycle
again, use `import type { ... }`

2020-09-04 22:14 UTC, bencpeters commented on packages/api/src/users/users.entity.ts
> +import { ReefToAdmin } from '../reefs/reef-to-admin.entity';
another `import type { }`

2020-09-04 22:14 UTC, bencpeters commented on packages/api/src/users/users.service.ts
> +          return Promise.resolve();
This is already an sync function, you don't need to return anything at all to get it to wrap in a `Promise` (or you could `return true` if that feels better)

2020-09-08 08:07 UTC, avalmas-programize commented on packages/api/src/reefs/reef-to-admin.entity.ts
> +// eslint-disable-next-line import/no-cycle
I removed all the lint disables from all the entities.
However the relations decorator expects a entity returned to use as a type for the relation.
To bypass this I had to change the way we declare a relationship from:
```js
@ManyToOne(() => Reef, (reef) => reef.reefToAdmin, { cascade: true })
reef: Reef;
```
to
```js
@ManyToOne<Reef>('Reef', (reef) => reef.reefToAdmin, { cascade: true })
reef: Reef;
```
But this does not solve all of the issues. After compiling the code an error appears in the dist files:
```
/home/antonios/Documents/Programize/aqualink-app-backend/packages/api/dist/src/reefs/reef-to-admin.entity.js
    __metadata("design:type", User)

ReferenceError: User is not defined
```
To solve this we have to create an interface for each entity and reference this as the type of the class member
https://github.com/typeorm/typeorm/issues/4190
Are we okay with this refactor?

2020-09-08 08:10 UTC, avalmas-programize commented on packages/api/src/reefs/reef-to-admin.entity.ts
> +export class ReefToAdmin {
I wanted to add a custom join table in case we need it in the future.
I will revert my change

2020-09-08 08:31 UTC, avalmas-programize commented on packages/api/src/auth/is-reef-admin.guard.ts
> +      const isReefAdmin = await this.reefToAdminRepository.findOne({
The routes this guard is added are the already protected ones, i.e the ones that do not allow the Default user to access them, only ReefManager and SuperAdmin.
In the first lines of this guard I bypass the guard if the level of the user is SuperAdmin.
So in this we are left with the case that the user is a ReefManager.
Also if in the future this is added to a not protected route, i.e a default user is tested to pass this check they will fail because the are not a manager of the reef, which makes perfect sense.
We should not allow a default user access more than a reef manager.

2020-09-08 08:31 UTC, avalmas-programize commented on packages/api/src/reefs/reefs.entity.ts
> +import { ReefToAdmin } from './reef-to-admin.entity';
Like I said this is more complicated than it seems.

2020-09-08 08:33 UTC, avalmas-programize commented on packages/api/src/surveys/surveys.entity.ts
> +// eslint-disable-next-line import/no-cycle
Like I said this is more complicated than it seems.

2020-09-08 08:33 UTC, avalmas-programize commented on packages/api/src/users/users.entity.ts
> +import { ReefToAdmin } from '../reefs/reef-to-admin.entity';
Like I said this is more complicated than it seems.

2020-09-08 08:38 UTC, avalmas-programize commented on packages/api/src/users/users.service.ts
> +          return Promise.resolve();
It was not letting me to just write `return;` because map expects something returned so I thought I could return an empty Promise since that's what I want.
But I will change it to null since I agree it is a bit ugly.

2020-09-08 10:37 UTC, avalmas-programize commented on packages/api/migration/1599209835916-AddReefToAdminTable.ts
> +        CONSTRAINT "PK_481618ed9eb45a5765dd8710596" PRIMARY KEY ("reef_to_admin_id")
Custom intermediate table has been deleted.
So these are by default primary keys now.

2020-09-08 10:38 UTC, avalmas-programize commented on packages/api/src/auth/is-reef-admin.guard.ts
> +    return true;
Hmm I thought it from a different angle, but I see your point. I will return false by default.

2020-09-08 10:42 UTC, avalmas-programize commented on packages/api/src/surveys/surveys.controller.ts
> +  @UseGuards(IsReefAdminGuard)
Interesting approach.
However I would name the decorator something more specific like `@ManagersOnly` because you would assume a `@Public` decorator to also have an affect to the `@Auth` decorator.

2020-09-08 10:58 UTC, avalmas-programize commented on packages/api/src/users/users.service.ts
> +    @InjectRepository(ReefToAdmin)
Added
GET users/current/administrated-reefs

2020-09-08 11:27 UTC, avalmas-programize commented on packages/api/src/surveys/surveys.controller.ts
> +  @UseGuards(IsReefAdminGuard)
Hmmm. IsReefAdminGuard needs the Auth decorator to run first and since the first one is now a Controller decorator it will always run first. So we need a different approach if we want to implement this.
We could edit the Auth decorator in order to dynamically add the IsReefAdminGuard to the list of decorators used or have the new decorator (the Public one you suggested) affect both guards' behavior and add those as global or controller decorators

2020-09-08 16:28 UTC, bencpeters commented on packages/api/src/reefs/reef-to-admin.entity.ts
> +// eslint-disable-next-line import/no-cycle
Ah, I see the issue, we need to actually use the types as a return value, not just a type annotation.

New plan: Since circular dependencies are pretty much baked into how TypeORM does many-to-many relations, let's add a new ESlint rule override to disable that check in `*.entity.ts` files only.

2020-09-08 16:31 UTC, bencpeters commented on packages/api/src/auth/is-reef-admin.guard.ts
> +      const isReefAdmin = await this.reefToAdminRepository.findOne({
That may be true in the current use-case - wherever we use this is already a protected route, but it would be fairly easy down the line for someone not to realize that. That's why I was suggesting adding an `adminLevel` check inside this guard so that you don't _have_ to ensure that a completely independent guard is also set whenever you use it.

2020-09-08 16:33 UTC, bencpeters commented on packages/api/src/surveys/surveys.controller.ts
> +  @UseGuards(IsReefAdminGuard)
> have the new decorator (the Public one you suggested) affect both guards' behavior and add those as global or controller decorators

This is what I was imagining. If you move `IsReefAdminGuard` to the controller level, you definitely have to move the Auth guard as well.

2020-09-08 16:46 UTC, bencpeters requested changes
Getting close!

A few small cleanups, then:

- for the cyclic dependencies, let's just leave them in the entity code, but add an eslint rule override for `*.entity.ts` files for that specific rule so that we don't need line-by-line overrides.
- For the `@Public` decorator - I think you'd need to have it affect the auth guard too, then it should work. I don't feel super strongly about it either way, but I generally think that it might be a cleaner way to define a controller where almost all the routes are protected but there are 1 or 2 public ones... if it's taking too long don't worry about it though.

2020-09-08 16:46 UTC, bencpeters commented on packages/api/src/users/users.controller.ts
> +    return this.usersService.getAdministratedReefs(req);
Let's call these "administered" (not "administrated") ([ref](https://site.uit.no/english/words/administrate/))

2020-09-08 16:46 UTC, bencpeters commented on packages/api/src/users/users.service.ts
> +        );
Can we add this relation from the "other side" (e.g. using the `userRepository`) instead? I think this is the only dependency the UserService has on the `reefRepository`, so if we could add it from the "other" side of the relation we could drop that dependency from this service...

```typescript
this.usersRepository.update({ id: user.id }, { administeredReefs: ... })
```
Maybe?

2020-09-08 16:46 UTC, bencpeters commented on packages/api/src/users/users.service.ts
> +    const reefEntities: Promise<UpdateResult | null>[] = reefAssociations.map(
Implicitly, a user who has user reef admin associations should also get the reef manager role, no?

2020-09-09 07:21 UTC, avalmas-programize commented on packages/api/src/reefs/reef-to-admin.entity.ts
> +// eslint-disable-next-line import/no-cycle
Okay

2020-09-10 06:53 UTC, avalmas-programize commented on packages/api/src/users/users.controller.ts
> +    return this.usersService.getAdministratedReefs(req);
Oops typo. Fixed

2020-09-10 08:27 UTC, avalmas-programize commented on packages/api/src/users/users.service.ts
> +        );
Done.

2020-09-10 08:28 UTC, avalmas-programize commented on packages/api/src/users/users.service.ts
> +    const reefEntities: Promise<UpdateResult | null>[] = reefAssociations.map(
Yeah I thought it would have been set from the application. Done.

2020-09-10 10:29 UTC, avalmas-programize commented
I have added the Public decorator. Implementation:
- Override method `AuthGuard('custom').canActivate` so that it will not apply the strategy if isPublic equals to true
- Override Levels and ReefAdmin guards to return true if isPublic equals to true
- Add OverrideLevelAccess decorator which overrides the level defined in the Auth decorator on the Controller in order to have different level of access per Controller
- Refactor Auth decorator in order for the above change to work without re-applying extra decorators

2020-09-11 03:49 UTC, ericboucher commented
When I tried it, I did not get promoted to "reef_manager" in the DB for some reason.

But I am actually wondering if this is still useful, if a user has a `reef - user` row, we can probably assume that they are an admin this way. And just keep `default` / `super_admin`

Thoughts @avalmas-programize @bencpeters

2020-09-11 08:15 UTC, avalmas-programize commented
No I think keeping all three roles is much useful and easier to maintain.
Also there was a bug regarding the promotion of the user to reef_manager.
Saves after the update operation for the user promotion were reverting the level of the user to their prior one.
Added a new commit that resolves this.

2020-09-11 08:48 UTC, ericboucher approved these changes

2020-09-11 08:57 UTC, ericboucher commented on packages/api/src/users/users.service.ts
> +    return this.usersRepository.save(newUser);
if we pass in an id, should we use .update instead of save?

2020-09-11 09:00 UTC, ericboucher commented on packages/api/src/users/users.service.ts
>        ...priorAccount,
should we reverse the order here so that priorAccount info is prioritized over the createUserDto?

2020-09-11 09:05 UTC, avalmas-programize commented on packages/api/src/users/users.service.ts
> +    return this.usersRepository.save(newUser);
Updating ManyToMany relations is not working with `update` only with `save`.
https://github.com/typeorm/typeorm/issues/2821

2020-09-11 09:06 UTC, avalmas-programize commented on packages/api/src/users/users.service.ts
>        ...priorAccount,
Do we want to do that?
I mean the createUserDto has the information added from the user in the registration form.

2020-09-11 10:08 UTC, merged