Delete survey button
aqualinkorg/aqualink-app pull request #154
Opened 2020-09-09 13:50 UTC by tleraj

This PR refers to https://github.com/aqualinkorg/aqualink-app/issues/142. The designs implemented look like this:

![Screenshot from 2020-09-09 16-48-51](https://user-images.githubusercontent.com/64922890/92607161-6e81df80-f2bc-11ea-8b23-237d564d3433.png)
![Screenshot from 2020-09-09 16-48-14](https://user-images.githubusercontent.com/64922890/92607165-6fb30c80-f2bc-11ea-8ba2-37b9fa89f071.png)
![Screenshot from 2020-09-09 16-49-47](https://user-images.githubusercontent.com/64922890/92607228-8194af80-f2bc-11ea-8111-2b7f0a755c0f.png)

2020-09-09 13:54 UTC, ericboucher requested changes
This looks like a complete overkill to me. We should be able to do this in just a few lines of code with https://material-ui.com/components/dialogs/

2020-09-09 15:34 UTC, ericboucher commented on packages/website/src/routes/ReefRoutes/Reef/Surveys/Timeline/index.tsx
> +                      <Grid
Let's make sure that only reef admins can see it?

2020-09-09 15:45 UTC, tleraj commented on packages/website/src/routes/ReefRoutes/Reef/Surveys/Timeline/index.tsx
> +                      <Grid
The button's visibility is set inside the component. Now it's only visible for `super_admin` or `reef_manager`.

2020-09-09 15:48 UTC, ericboucher commented on packages/website/src/routes/ReefRoutes/Reef/Surveys/DeleteButton.tsx
> +      borderBottom: "1px solid black",
I don't like this border

2020-09-09 15:48 UTC, ericboucher commented on packages/website/src/routes/ReefRoutes/Reef/Surveys/Timeline/index.tsx
> +                      <Grid
Why set it inside the component? I think it probably makes more sense within the Surveys? Maybe set an `isAdmin` flag that we can use to show/hide the create survey option and the delete options?

2020-09-09 23:35 UTC, bencpeters requested changes
Minor clean-ups. I'm also wondering what the purpose of passing in `isAdmin` from the higher component is? It seems like all that accomplishes is establish a new redux dependency (on user) in a higher level component, which is going to mean that the whole component (`ReefDetails` or `NewSurvey`) re-renders on every change to the user redux slice. It may not matter _that_ much in this case since I don't know that the state changes much, but I don't see any reason to hoist that dependency "higher" in the tree than it needs to be here?

2020-09-09 23:35 UTC, bencpeters commented on packages/website/src/routes/ReefRoutes/Reef/Surveys/Timeline/index.tsx
> +                        {isAdmin && (
This check should be one level higher - there's no reason to render the `Grid.buttonContainer` if `isAdmin` is `false`...

2020-09-09 23:35 UTC, bencpeters commented on packages/website/src/routes/ReefRoutes/Reef/Surveys/TimelineMobile/index.tsx
> +                    {isAdmin && (
This check should be one level higher

2020-09-10 14:03 UTC, ericboucher commented on packages/website/src/routes/ReefRoutes/Reef/Surveys/TimelineMobile/index.tsx
> +                    {isAdmin && (
@tleraj Ben means that ths isAdmin should be set on the grid rather than the button

2020-09-10 15:34 UTC, ericboucher approved these changes

2020-09-10 15:56 UTC, merged