Allow reef managers to update featured media
aqualinkorg/aqualink-app pull request #265
Opened 2020-09-29 13:13 UTC by tleraj

This PR is scheduled to fix https://github.com/aqualinkorg/aqualink-app/issues/171.

2020-09-29 22:33 UTC, ericboucher commented on packages/website/src/routes/Surveys/View/index.tsx
> +            <SurveyMediaDetails
If isAdmin is only used in SurveyMediaDetails, then let's move the `const user = useSelector(userInfoSelector);` into `SurveyMediaDetails`

And maybe create a util function `isUserAdmin(user)` and use it where we had a similar isAdmin as well so that it's easier to manage?

2020-09-29 22:35 UTC, ericboucher requested changes
See comments inline

2020-09-30 11:53 UTC, tleraj commented on packages/website/src/routes/Surveys/View/index.tsx
> +            <SurveyMediaDetails
`user` is also needed in `onSurveyMediaUpdate`, so if we moved it into the `SurveyMediaDetails`, then we would have to also move the `onSurveyMediaUpdate` function, along with the `reefId`. Does this sound good?

2020-09-30 12:38 UTC, ericboucher commented on packages/website/src/routes/Surveys/View/index.tsx
> +            <SurveyMediaDetails
If it's easy to move `onSurveyMediaUpdate` I would say let's do that. If it's not easy then it's ok to keep it here.

2020-10-01 10:43 UTC, ericboucher approved these changes

2020-10-01 11:09 UTC, merged