Display Spotter Data
aqualinkorg/aqualink-app pull request #337
Opened 2020-10-22 15:47 UTC by tleraj

The purpose of this PR is to display data coming from the Smart Buoy on a chart.

2020-10-30 07:41 UTC, SimplyBallistic requested changes

2020-10-30 07:41 UTC, SimplyBallistic commented on packages/website/src/common/Chart/Tooltip/index.tsx
> +              {!spotterSurfaceTemp &&
TODO compress 83 with 99

2020-10-30 07:41 UTC, SimplyBallistic commented on packages/website/src/common/Chart/utils.ts
> +    d1.getFullYear() === d2.getFullYear() &&
Could use to date string here

2020-10-30 07:41 UTC, SimplyBallistic commented on packages/website/src/common/SelectRange/index.tsx
> +  onRangeChange: (event: ChangeEvent<{ value: unknown }>) => void;
TODO investigate unknown type

2020-10-30 07:41 UTC, SimplyBallistic commented on packages/website/src/helpers/dates.ts
> +    default:
Line could be removed with rearranged cases

2020-10-30 07:41 UTC, SimplyBallistic commented on packages/website/src/helpers/dates.ts
> +      return "day";
Same as 12

2020-10-30 07:41 UTC, SimplyBallistic commented on packages/website/src/routes/ReefRoutes/Reef/ReefDetails.tsx
> +/* eslint-disable no-nested-ternary */
TODO move to site

2020-10-30 07:41 UTC, SimplyBallistic commented on packages/website/src/routes/ReefRoutes/Reef/index.tsx
> +  const todayDate = new Date(
TODO simplify

2020-10-30 07:41 UTC, SimplyBallistic commented on packages/website/src/routes/Surveys/View/index.tsx
> +/* eslint-disable no-nested-ternary */
Move to site

2020-10-30 07:41 UTC, SimplyBallistic commented on packages/website/src/routes/Surveys/View/index.tsx
> +                    <Grid container alignItems="center" item xs={11}>
Repeat from reefs page. TODO investigate if possible to merge

2020-10-30 07:41 UTC, SimplyBallistic commented on packages/website/src/store/Reefs/selectedReefSlice.ts
> +export const reefspotterDataLoadingSelector = (
Casing

2020-11-02 15:31 UTC, SimplyBallistic commented on packages/website/src/routes/ReefRoutes/Reef/ReefDetails.tsx
> -                  dailyData={filteredDailyData}
@tleraj wondering what `filteredDailyData` was for? After replacing it with the full set, the x axis still works fine since axis limits is calculated strongly by spotter data.

2020-11-02 15:37 UTC, tleraj commented on packages/website/src/routes/ReefRoutes/Reef/ReefDetails.tsx
> -                  dailyData={filteredDailyData}
It had more to do with the yAxis limits. In order to calculate the yAxis limits we only need to consider the data inside the `[startDate, endDate]` time window. I thought we don't want any data outside this window to affect the yAxis limits calculation.

2020-11-02 15:40 UTC, tleraj commented on packages/website/src/common/Chart/index.tsx
>                min: xAxisMin,
Shouldn't this also be `min: startDate || xAxisMin`?

2020-11-02 19:40 UTC, ericboucher commented on packages/website/src/common/Chart/index.tsx
>                min: xAxisMin,
If we are doing the filtering properly it should be pretty much the same thing and it ensures that we have a clean start

2020-11-02 22:57 UTC, SimplyBallistic commented on packages/website/src/routes/ReefRoutes/Reef/ReefDetails.tsx
> -                  dailyData={filteredDailyData}
Ahh I see! I'll move this to the utils file, think it's better to try do all this processing in one place in a coherence sense. Shouldn't be too hard since we pass start date and end date to chart

2020-11-03 01:43 UTC, SimplyBallistic commented on packages/website/src/common/Chart/index.tsx
>                min: xAxisMin,
Would that mean `endDate || xAxisMax` is also not needed? Tried removing it and the chart functioned the same. What cases might `endDate` here be used?

2020-11-03 18:48 UTC, ericboucher commented on packages/website/src/common/Chart/index.tsx
>                min: xAxisMin,
Yeah that's probably fine I think

2020-11-05 03:01 UTC, SimplyBallistic approved these changes

2020-11-05 03:08 UTC, SimplyBallistic commented on packages/website/src/common/Chart/Tooltip/index.tsx
> +              {spotterSurfaceTemp ? " UTC" : ""}
Maybe `{spotterSurfaceTemp && " UTC"}` might work here?

2020-11-05 03:08 UTC, SimplyBallistic commented on packages/website/src/common/Chart/Tooltip/index.tsx
> +const TemperatureMetric = (
Converting this to a component might be the best. Otherwise it works fine :)

2020-11-05 03:08 UTC, SimplyBallistic commented on packages/website/src/common/Chart/index.tsx
> +              max: endDate || xAxisMax,
TODO remove

2020-11-05 03:18 UTC, SimplyBallistic commented
The survey chart and reef details chart are very similar, should we make a component to combine them?
| Reef Details | Surveys |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/25571542/98193552-9d8d9800-1f71-11eb-84fd-3538d1bef99f.png) | ![image](https://user-images.githubusercontent.com/25571542/98193567-a67e6980-1f71-11eb-9b3b-721d16ce4d85.png) |

Also, survey charts look broken

2020-11-05 03:47 UTC, SimplyBallistic commented on packages/website/src/common/Chart/index.tsx
> +              max: endDate || xAxisMax,
The survey chart acts strangely without this check, since there's no spotter data for 5th August (and limits can't be calculated without). I say keep it for now...

2020-11-05 04:42 UTC, merged