Add ping cloud function and healthCheck endpoint
aqualinkorg/aqualink-app pull request #362
Opened 2020-11-09 11:30 UTC by avalmas-programize

Add ping cloud function
Add healthCheck module and controller (used as a simple ping endpoint):
- GET /health-check: Return { status: 200 }

2020-11-09 19:35 UTC, ericboucher commented on packages/api/cloud-functions/index.ts
> +  .runWith({ timeoutSeconds: 540 })
I don't think we need a 9min timeout for this

2020-11-09 19:35 UTC, ericboucher commented on packages/api/cloud-functions/index.ts
> +  .timeZone('America/Los_Angeles')
no need for a timezone either

2020-11-09 19:38 UTC, ericboucher commented
@avalmas-programize let's make sure you update the README command with the new variable:


export $(grep -v '^#' .env.staging | xargs) && firebase functions:config:set database.url=$DATABASE_URL sofar_api.token=$SOFAR_API_TOKEN ...

2020-11-09 19:39 UTC, ericboucher requested changes
See inline comments + add env_variable

2020-11-10 08:25 UTC, avalmas-programize commented on packages/api/cloud-functions/index.ts
> +  .timeZone('America/Los_Angeles')
Ok

2020-11-10 08:25 UTC, avalmas-programize commented on packages/api/cloud-functions/index.ts
> +  .runWith({ timeoutSeconds: 540 })
Ok

2020-11-10 17:26 UTC, ericboucher approved these changes

2020-11-10 17:37 UTC, merged