Improve responsiveness through MUI theme configuration
aqualinkorg/aqualink-app pull request #372
Opened 2020-11-25 13:24 UTC by tleraj

This PR is scheduled to fix https://github.com/aqualinkorg/aqualink-app/issues/352.

2020-12-15 00:25 UTC, Ry-DS requested changes
Just a few suggestions. @ericboucher feel free to weigh in on these if you think they aren't too concerning!

2020-12-15 00:25 UTC, Ry-DS commented on packages/website/src/layout/App/theme.ts
> +// eslint-disable-next-line fp/no-mutation
A better way to do this might be to create an empty theme `const breakpointTheme = createMuiTheme({})` and just use that in the above theme whenever you need breakpoints.

2020-12-15 00:25 UTC, Ry-DS commented on packages/website/src/routes/Landing/index.tsx
> +        height: "36rem",
Not too sure if this is a big concern, but wouldn't it be better to use a unit besides `rem` or `em`? Since these units are for font sizes, don't see why the image should be relative to those. Maybe a `%` or a set `px` would work better so the image height is more predictable.

2020-12-15 00:25 UTC, Ry-DS commented on packages/website/src/routes/Surveys/View/SurveyDetails.tsx
> +      style={{ marginTop: "1rem" }}
Unless the grid is closely related to text (there's text above it maybe) it might be best to do a set value so the value is more predictable. If the global font size changes, this will change too.

2020-12-15 00:27 UTC, Ry-DS commented on packages/website/src/layout/App/theme.ts
> +// eslint-disable-next-line fp/no-mutation
Found a better solution to mine on stack overflow: https://stackoverflow.com/a/56370022/5279269

2020-12-15 00:37 UTC, Ry-DS commented
have this deployed? Since there's a global mui style change, would be nice to make sure everything still looks good on mobile :+1:
Or if you can confirm this yourself that would be great too :)

2020-12-15 03:37 UTC, ericboucher commented
@Ry-DS just deployed on staging - https://aqualink-app-staging.web.app/

2020-12-16 11:57 UTC, Ry-DS commented
> @Ry-DS just deployed on staging - https://aqualink-app-staging.web.app/. It might take a hard reload to update.

Looks good overall! Here are some small fixes that could be done on the `/drones` page:
| 1 | 2 |
| - | - |
| ![image](https://user-images.githubusercontent.com/25571542/102345647-d3eb1800-3ff1-11eb-968b-81a0b4e88fb6.png) | ![image](https://user-images.githubusercontent.com/25571542/102345711-e82f1500-3ff1-11eb-8653-b440e109fcee.png) |

The blue cards could be centered maybe?

2020-12-16 12:24 UTC, Ry-DS requested changes
A few suggestions :+1:

2020-12-16 12:24 UTC, Ry-DS commented on packages/website/src/routes/Landing/index.tsx
> +          top="calc(100vh - 64px)"
Is it a coincidence that this and line 158 match exactly? If not, introducing a variable to store this value or maybe just a small comment explaining why they are the same would be great!

2020-12-16 12:24 UTC, Ry-DS commented on packages/website/src/routes/Landing/index.tsx
> +  const seeMore = useCallback(() => {
`useCallback` should *never* be used unless you're passing the function to a dependency array; it may actually decrease performance if its not used with `useEffect` or anything else that uses dependency arrays :)

2020-12-16 12:24 UTC, Ry-DS commented on packages/website/src/routes/Landing/index.tsx
> +  const isMobile = windowSize && windowSize.width < MOBILE_SIZE;
Optional Chaining could be used here, but you might be replacing this anyway from the above comment...

2020-12-16 12:24 UTC, Ry-DS commented on packages/website/src/routes/Landing/index.tsx
> +          padding="0 10px 0 10px"
Would `padding: 0 10px` work here?

2020-12-16 12:24 UTC, Ry-DS commented on packages/website/src/routes/Landing/index.tsx
> +const MOBILE_SIZE = 600;
You should use this: https://material-ui.com/components/use-media-query/
instead of a hard coded mobile size.

2020-12-16 12:24 UTC, Ry-DS commented on packages/website/src/routes/Landing/index.tsx
> +  const handleScroll = useCallback(() => {
You could just define this inside the `useEffect` itself, since (I think) its not used anywhere else, and remove `useCallback`. Or just remove `useCallback` since the performance impact would be negligible.

2020-12-16 13:55 UTC, tleraj commented on packages/website/src/routes/Landing/index.tsx
> +          top="calc(100vh - 64px)"
It just so happens here that the button and the navbar have roughly the same height. Here I place the button at the bottom of the screen (so `100vh` minus the button's height which is `56px` but I add a little more so that it doesn't touch the bottom edge of the screen). In line 158, I want the image's height to be `100vh` minus the height of the navbar. I added comments on both just to be clear :slightly_smiling_face:

2020-12-20 08:42 UTC, Ry-DS approved these changes
Looks good!

2020-12-20 08:42 UTC, Ry-DS commented on packages/website/src/routes/Surveys/View/SurveyDetails.tsx
> +      style={{ marginTop: 16 }}
Can't remember off the top of my head if `Grid` supports prop spacing like `Box` does. If possible, replacing this with `<Grid marginTop={X}\>` would be great. Otherwise, this is fine too :+1:

2020-12-20 08:42 UTC, Ry-DS commented on packages/website/src/routes/Landing/index.tsx
> +          <Fab onClick={seeMore} size="large">
Out of curiosity, how do I trigger this button? I tried the link Eric sent on mobile but couldn't find this button. Is the link outdated? Otherwise if it works fine on your end all is good :+1:

2020-12-21 11:25 UTC, tleraj commented on packages/website/src/routes/Landing/index.tsx
> +          <Fab onClick={seeMore} size="large">
I noticed this too, that's why I changed position from `absolute` to `fixed` and set it's `bottom` to `10px`. So the content in the link is outdated. We need a re-deployment :+1:

2020-12-21 21:52 UTC, ericboucher commented on packages/website/src/routes/Landing/index.tsx
> +          <Fab onClick={seeMore} size="large">
Deployed on staging, I still don't see it though

2020-12-22 13:35 UTC, tleraj commented on packages/website/src/routes/Landing/index.tsx
> +          <Fab onClick={seeMore} size="large">
I'm not sure why it doesn't work for you. It appears to work for me:
| My device | Browser responsive |
|---|---|
| ![Screenshot_2020-12-22-15-28-38-159_com android chrome](https://user-images.githubusercontent.com/64922890/102893872-e9859500-446a-11eb-99bd-28eea8f63e53.jpg)  | ![Screenshot_20201222_153308](https://user-images.githubusercontent.com/64922890/102894071-349fa800-446b-11eb-9cfa-2aed0702751c.png) |

2020-12-22 13:54 UTC, tleraj commented on packages/website/src/routes/Landing/index.tsx
> +          <Fab onClick={seeMore} size="large">
I added a `zIndex` of 100 so now it should be working

2020-12-22 16:55 UTC, ericboucher approved these changes

2020-12-22 17:22 UTC, merged