Handle timezones
aqualinkorg/aqualink-app pull request #451
Opened 2021-02-02 19:32 UTC by tleraj

The purpose of this PR is to close https://github.com/aqualinkorg/aqualink-app/issues/384.

2021-02-03 17:47 UTC, tleraj commented
So the thing that caused the deprecation warning was that we were using `moment(convertToLocalTime(...)).format(...)`, but moment accepts only ISO formatted strings and `convertToLocalTime(...)` didn't return such a string. I removed all `convertTo...` utils and changed `displayTimeInLocalTimezone` so that it accepts a desired format which is then passed to `moment`. Now all the dates are in ISO format, but when they are being displayed, they are displayed in the reef's local time thanks to `displayTimeInLocalTimezone`. @ericboucher @Ry-DS Let me know what you think :slightly_smiling_face:

2021-02-04 02:44 UTC, ericboucher commented on packages/website/src/helpers/dates.ts
> -export const convertDailyDataToLocalTime = (
@tleraj We still need a way to convert data before passing it to chartjs no? Otherwise the tooltip data and chartjs axis won't line up. Or do we have other ways to shift the timezone that chartjs is using to display the charts?

2021-02-08 18:48 UTC, tleraj commented on packages/website/src/helpers/dates.ts
> -export const convertDailyDataToLocalTime = (
I found out that `moment(isoDate).tz(timeZone).format()` returns an ISOish date. For example, `2021-01-31T23:59:59.999Z` becomes `2021-01-31T18:59:59-05:00` with an `America/New_York` timezone. So having this in mind, I recreated the `convert...` methods and tried to convert the data before passing them to the charts. But for some reason, chart js does not understand this new format, and displays data in the initial ISO format.

2021-02-11 17:51 UTC, ericboucher commented on packages/website/src/common/Chart/Tooltip/index.tsx
> +    timeZone: userTimeZone,
why do we need this change in the tooltip? The tooltip was working well, no?

2021-02-14 18:17 UTC, ericboucher commented on packages/website/src/common/Chart/Tooltip/index.tsx
> +  // const dateString = hourlyData ? date : moment(date).format("MM/DD/YY");
👣

2021-02-15 12:06 UTC, tleraj commented
Made some final changes so that the picker's date corresponds to site's local time.

2021-02-15 12:10 UTC, tleraj commented on packages/website/src/common/Chart/Tooltip/index.tsx
> +    timeZone: userTimeZone,
The chart data correspond to user's local time zone. So the first parameter (`timeZone`) is the time zone we want to process the date with, and the second parameter (`timeZoneToDisplay`) is the time zone we want to be finally displayed (the site's time zone).

2021-02-15 22:49 UTC, Ry-DS reviewed
Suggestions to improve readability :+1:

2021-02-16 23:58 UTC, ericboucher approved these changes

2021-02-17 01:25 UTC, ericboucher requested changes
What we see now is different than what we had an I don't understand why.

Can we add tests to the different time shift functions maybe?

Currently on prod:
<img width="1307" alt="Screen Shot 2021-02-16 at 5 21 56 PM" src="https://user-images.githubusercontent.com/16843267/108142999-b41cb280-707b-11eb-8612-4cd3fa19e894.png">

With this version:
<img width="1392" alt="Screen Shot 2021-02-16 at 5 21 40 PM" src="https://user-images.githubusercontent.com/16843267/108143004-b54ddf80-707b-11eb-9b13-d544406ce3e5.png">

2021-02-17 07:12 UTC, ericboucher approved these changes

2021-02-17 07:12 UTC, merged