Develop 508 map reef zoom params support
aqualinkorg/aqualink-app pull request #512
Opened 2021-04-03 22:14 UTC by abouillis

This branch was created on top of the PR #509. It must be merged after the PR #509 approvment.

2021-04-04 00:07 UTC, ericboucher commented on packages/website/src/routes/HomeMap/Map/index.tsx
> +  const zoom: number = zoomParam ? +zoomParam : INITIAL_ZOOM;
You need to find a safer way to do this. Currently, entering zoom=hello breaks the app

2021-04-04 00:12 UTC, ericboucher requested changes
This is a great start!

Let's make sure that the url params are parsed in a safe way to avoid any errors. See comments inline.

And keep the current behavior of the app, on start, we want to zoom to the reef_id but NOT open the tooltip.

2021-04-04 00:12 UTC, ericboucher commented on packages/website/src/routes/HomeMap/Map/index.tsx
> +  const zoom: number = zoomParam ? +zoomParam : INITIAL_ZOOM;
You will need to find a safer way to do this. Currently, entering zoom=hello breaks the app

2021-04-04 00:12 UTC, ericboucher commented on packages/website/src/routes/HomeMap/index.tsx
> +  return query.get("reef_id") || process.env.REACT_APP_FEATURED_REEF_ID || "";
Same here, you will need to make sure that the ID is valid AND that it is indeed in the list of available reefs. If you enter a random reef_id, then the `Selected Site` section stays empty and we get 400 errors from the backend in the console.

2021-04-05 21:11 UTC, abouillis commented on packages/website/src/routes/HomeMap/Map/index.tsx
> +  const zoom: number = zoomParam ? +zoomParam : INITIAL_ZOOM;
I changed the zoom parameter management.

2021-04-05 21:14 UTC, abouillis commented on packages/website/src/routes/HomeMap/index.tsx
> +  return query.get("reef_id") || process.env.REACT_APP_FEATURED_REEF_ID || "";
I completely changed the way I process the reef_id param and I add the reef existence checking.

2021-04-05 22:41 UTC, ericboucher commented on packages/website/src/routes/HomeMap/index.tsx
> +  return reefsList.length > 0 && featuredReefId && !featuredReef ? (
I'm not a huge fan of the "not found" here. I think I would prefer to test if the queryParam reef_id is in the reefsList, and if not default to `REACT_APP_FEATURED_REEF_ID`. And not change the current behavior.

Note that the current default behavior is to focus on the reef with the worst alert level (most dire situation). And the featuredReef is independent from that zoom. We want to keep that behavior as the default. The behavior should only change if there is a reef_id URL parameter.

2021-04-05 22:44 UTC, ericboucher commented on packages/website/src/routes/HomeMap/index.tsx
> +  return reefsList.length > 0 && featuredReefId && !featuredReef ? (
Testing for reef_id in reefsList will also help you avoid dispatching a reef that you know doesn't exist and get 400 responses from the backend

Eg `http://localhost:3000/map?reef_id=hello` creates requests to the backend and of course gets 400s back

2021-04-06 21:34 UTC, abouillis commented on packages/website/src/routes/HomeMap/index.tsx
> +  return reefsList.length > 0 && featuredReefId && !featuredReef ? (
Ok, thanks for your feedback, I didn't really understand what's the purpose of the featured reef versus the reef_id URL parameter. It's a bit more clear now. I just pushed a update where I removed the "not found" and set the behaviour you described.

2021-04-07 11:47 UTC, Ry-DS reviewed
Coming along well! A few suggestions:

2021-04-07 11:47 UTC, Ry-DS commented on packages/website/src/routes/HomeMap/Map/index.tsx
> +type HomepageMapProps = WithStyles<typeof styles> & { zoomLevel: number };
If we are adding props, we should make a new interface to hold these props
```ts
interface HomepageMapIncomingProps {
    zoomLevel: number;
}
```

2021-04-07 11:47 UTC, Ry-DS commented on packages/website/src/routes/HomeMap/index.tsx
> +  zoomLevel = "zoom",
Maybe case enum constants as `ZOOM_LEVEL` and `REEF_ID`? Not too important, up to you :)

2021-04-07 11:47 UTC, Ry-DS commented on packages/website/src/routes/HomeMap/index.tsx
> +  const reefsList = useSelector(reefsListSelector) || [];
I like this approach, but I feel this should all be moved into a hook, since this code could really be anywhere (not dependant on HomeMap). Doing so will clean things up and help make this feature easier to track. Maybe you can expand the new `useQuery` hook?

2021-04-07 11:47 UTC, Ry-DS commented on packages/website/src/routes/HomeMap/index.tsx
> +  }, [dispatch, featuredReefId, reefOnMap]);
Was this from eslint? Surprised it wasn't caught before

2021-04-07 11:47 UTC, Ry-DS commented on packages/website/src/routes/HomeMap/Map/index.tsx
> +type HomepageMapProps = WithStyles<typeof styles> & { zoomLevel: number };
Also, maybe we name this `initialZoom`? One might think changing this value actively changes the zoom.

2021-04-07 11:47 UTC, Ry-DS commented on packages/website/src/routes/HomeMap/Map/Markers/index.tsx
>                    dispatch(setReefOnMap(reef));
this is a longshot, but maybe we can unset the initial reef with `setReefOnMap`? Might not work for all cases but might be worth a shot since it seems like everywhere `setReefOnMap` is, `unsetMapInitialReef` follows.

2021-04-07 16:36 UTC, tleraj reviewed
Looks good. Just some comments along with @Ry-DS's suggestions :slightly_smiling_face:

2021-04-07 16:36 UTC, tleraj commented on packages/website/src/routes/HomeMap/index.tsx
> +      dispatch(setMapInitialReef(queryParamReef));
Not sure why we need `mapInitialReef`. It seems that wherever we `setMapInitialReef` we also `setReefOnMap`, and same with `unsetMapInitialReef`. I feel like we could achieve our goal by using only `reefOnMap`. If there is a deeper reason, then ignore this :slightly_smiling_face:

2021-04-07 16:36 UTC, tleraj commented on packages/website/src/routes/HomeMap/Map/Markers/index.tsx
> +                    reef.id !== (initialReef ? initialReef.id : 0)
Not sure if it could possibly happen, but what if there is a reef with id 0? Maybe
```javascript
reef.id !== initialReef?.id
```

2021-04-07 16:36 UTC, tleraj commented on packages/website/src/routes/HomeMap/ReefTable/body.tsx
> +    dispatch(unsetMapInitialReef());
Same as my comment above

2021-04-07 21:14 UTC, ericboucher commented
@abouillis the implementation was causing a weird behavior because of a conflict between the findMaxAlertReefPosition and the new reefId initialization so I tried another approach. Let me know what you think. Last thing to wrap up is address Ryan's comment and extract the hook and we should be good to go!

2021-04-07 21:14 UTC, ericboucher approved these changes

2021-04-07 22:45 UTC, abouillis commented on packages/website/src/routes/HomeMap/index.tsx
> +  }, [dispatch, featuredReefId, reefOnMap]);
Yes, I had to add featuredReefId to clear the eslint warning.

2021-04-07 23:29 UTC, abouillis commented
@ericboucher ok I understand your approach, it's more clear. I try it but I didn't take that way, because without using setReefOnMap, the reef is not selected into the reefs list at the bottom right. I thought it was important for the screen consistence. setReefOnMap seems to centralize the triggering of the behaviours of all the components. N.B: You still have a strange behaviour I noticed: when the reef_id parameter is used, there is a double data initialization into the "Selected site" block, one to load the featured reef's data, and another to load the reef from the reef_id parameter. It finalize with a delay after the full page display.

2021-04-07 23:54 UTC, abouillis commented on packages/website/src/routes/HomeMap/index.tsx
> +  const reefsList = useSelector(reefsListSelector) || [];
I moved the parameters processing into the useQuery hook.

2021-04-07 23:56 UTC, abouillis commented
@ericboucher I moved the parameters processing into the useQuery hook.

2021-04-08 00:36 UTC, ericboucher commented
Good catch! Any idea where it could come from? I'll try to track it down.

And good point on the screen consistency. I think it is fine for now to keep things simpler.

2021-04-08 00:44 UTC, ericboucher commented
I think I got it, we didn't check that the reefList was loaded before loading the featuredReef but we wait for the list to check the existence of the initialReef which is causing a double fetch. I have a fix in progress

2021-04-08 01:19 UTC, ericboucher commented
@abouillis I think I fixed it but I am not sure this is the most efficient! Any ideas on how to improve the efficiency/speed of the first load?

2021-04-08 17:07 UTC, tleraj commented on packages/website/src/routes/HomeMap/index.tsx
> +      ""
Is this necessary? Couldn't we just say
```javascript
const initialReefId = queryParamReefId
    ? findReefById(reefsList, queryParamReefId)?.id.toString() ||
      findReefById(reefsList, featuredReefId)?.id.toString()
    : featuredReefId;
```

2021-04-08 17:10 UTC, ericboucher commented on packages/website/src/routes/HomeMap/index.tsx
> +      ""
no because the queryParamId could be a fake input, eg. "hello" but exist
and the featuredId not exist = "426225" so we would end up with an undefined

2021-04-08 17:13 UTC, merged

2021-04-08 21:50 UTC, abouillis commented
@ericboucher I think it was a good way but I think we could improve the first load.
I noticed there is a double call to the reefs endpoint. 

I found a useEffect hook containing an explicit call with dispatch(reefsRequest()); into the HomeMap and the ReefList components.

Is that useEffect hook really needed into the both components? I tried to remove them without visible behaviour change.