Make user email case insensitive
aqualinkorg/aqualink-app pull request #516
Opened 2021-04-05 12:27 UTC by avalmas-programize

https://github.com/aqualinkorg/aqualink-app/issues/510

2021-04-05 16:27 UTC, ericboucher commented on packages/api/src/users/users.service.ts
> +    if (
So do we know what was happening? Firebase always return the email in lowercase?

2021-04-05 16:47 UTC, ericboucher commented
@tleraj maybe we could also solve this in the frontend actually and make sure the email input are of type `email` to control the case.

2021-04-06 07:53 UTC, avalmas-programize commented on packages/api/src/users/users.service.ts
> +    if (
Yes all user emails are stored in firebase in lowercase

2021-04-06 10:07 UTC, avalmas-programize commented
Since we plan to expose the backend API to the public we need have checks in the backend as well

2021-04-06 10:10 UTC, avalmas-programize commented
Class/validator has a guard `IsLowercase` that we can use. Quite unexpected but also quite handy
So this will simplify the backend checks

2021-04-06 16:13 UTC, ericboucher commented on packages/website/src/common/RegisterDialog/index.tsx
> +        email: data.emailAddress.toLowerCase(),
Ideally we can only type lowercase (eg. ovio.org)

Or at least also transform to lowercase in the sign in

2021-04-06 17:10 UTC, tleraj commented
@ericboucher With the latest change, the input value on the email text field is always transformed into lowercase (in both sign in and sign up dialogs) by using a `react-hook-form` workaround
```javascript
onChange={() =>
  setValue(
    "emailAddress",
    getValues("emailAddress").toLowerCase()
  )
}
```

Also the values in the request payloads on the submit functions are transformed into lowercase just in case.

2021-04-07 17:05 UTC, tleraj approved these changes
Looks good :+1:

2021-04-07 17:43 UTC, ericboucher requested changes
Let's make the backend safe instead of using guards

2021-04-08 16:39 UTC, ericboucher approved these changes

2021-04-08 17:26 UTC, ericboucher approved these changes

2021-04-08 17:30 UTC, merged