Implement Dashboard Designs
aqualinkorg/aqualink-app pull request #530
Opened 2021-04-14 16:43 UTC by tleraj

The purpose of this PR is to close https://github.com/aqualinkorg/aqualink-app/issues/529.
Working example at https://aqualink-app-programize.web.app/ (select `Dashboard` from user drop down menu at top right)

#### Design
| desktop | iPad Pro | iPad | iPhone 6/7/8 |
|---|---|---|---|
| ![screencapture-localhost-3000-dashboard-2021-04-14-19_37_38](https://user-images.githubusercontent.com/64922890/114747403-7bd2e100-9d59-11eb-834f-d3f0de416851.png) | ![screencapture-localhost-3000-dashboard-2021-04-14-19_38_11](https://user-images.githubusercontent.com/64922890/114747462-88efd000-9d59-11eb-9d01-5a360d433507.png) | ![screencapture-localhost-3000-dashboard-2021-04-14-19_39_09](https://user-images.githubusercontent.com/64922890/114747492-91e0a180-9d59-11eb-98e2-826d4e6d4eaa.png) | ![screencapture-localhost-3000-dashboard-2021-04-14-19_39_27](https://user-images.githubusercontent.com/64922890/114747531-9a38dc80-9d59-11eb-8ab6-e63270a67d66.png) |

2021-04-15 11:02 UTC, avalmas-programize commented
Query from the `latestData` view is a bit slow

2021-04-21 23:44 UTC, ericboucher commented on packages/api/src/collections/collections.service.ts
> +    const mappedReefData = collection.reefs.reduce((obj, reef) => {
Can we use a more telling name than `obj`? :)

2021-04-21 23:45 UTC, ericboucher commented on packages/api/src/collections/dto/filter-public-collcetion.dto.ts
> +import { IsNumber, IsOptional, IsString, Validate } from 'class-validator';
file name typo

2021-04-21 23:48 UTC, ericboucher commented on packages/api/src/utils/time-series.utils.ts
> +import { Metric } from '../time-series/metrics.entity';
Why do we need this?

2021-04-21 23:57 UTC, ericboucher commented on packages/website/src/helpers/map.ts
> +      return sensorIcon("spotter", selected, color);
This should just be one case:

`case hasSpotter:`

2021-04-21 23:57 UTC, ericboucher commented on packages/website/src/helpers/map.ts
> +    case !hasSpotter && hasHobo:
And this should just be one case:

`case hasHobo`:

2021-04-21 23:58 UTC, ericboucher commented on packages/website/src/mocks/mockReef.ts
> +  admins: [],
why no admins?

2021-04-21 23:58 UTC, ericboucher commented on packages/website/src/mocks/mockReef.ts
> +  admins: [],
why no admins?

2021-04-22 00:01 UTC, ericboucher commented on packages/website/src/layout/App/index.tsx
> +                />
Instead of doing this, make the route process as:

`/collections/$collectionName`

And create a file Collections.tsx that handles the `collectionName` argument with a map:

{collectionName: collectionId}

2021-04-22 00:03 UTC, ericboucher commented on packages/website/src/routes/Dashboard/Content.tsx
> +const FEATURED_COLLECTION_ID = "1";
See comments abouthe the collection url parsing `collectionName` with a map

2021-04-22 00:04 UTC, ericboucher commented on packages/website/src/layout/App/index.tsx
> +                />
Or handle it in Dashboard content if you prefer

2021-04-22 00:05 UTC, ericboucher commented on packages/website/src/routes/Dashboard/BackButton/index.tsx
> +import React from "react";
The name of the file is misleading. This is more than a BackButton, no?

2021-04-22 00:06 UTC, ericboucher commented on packages/website/src/routes/Dashboard/BackButton/index.tsx
> +          <Button component={Link} to="/map">
I thought we mentioned that we would go back to the previous page if it's in the app?

2021-04-22 00:07 UTC, ericboucher commented on packages/website/src/routes/Dashboard/Content.tsx
> +  const { collection: signedInUserCollection } = signedInUser || {};
The prefix "static" seems a bit unnecessary now that the data actually comes from the DB. Let's get rid of it

2021-04-22 00:09 UTC, ericboucher commented on packages/website/src/routes/Dashboard/index.tsx
> +/* eslint-disable no-nested-ternary */
Let's avoid top of file eslint-disable but instead use a next-line disable

2021-04-22 00:13 UTC, ericboucher commented on packages/website/src/routes/Dashboard/index.tsx
> +        ) : null}
This logic seems over complicated. 


Let's see what you can do to simplify after we have streamlined the way we load a collection..

2021-04-22 00:15 UTC, ericboucher commented on packages/website/src/routes/HomeMap/Map/Markers/index.tsx
> +        disableClusteringAtZoom={collection ? 1 : 2}
Is this necessary? Is it even being used?

2021-04-22 00:16 UTC, ericboucher commented on packages/website/src/routes/HomeMap/Map/Markers/index.tsx
> +            const { weeklyAlert } = reef.collectionData || {};
This feels a bit odd. Why would we have one but not the other? Shouldn't they have the same name if they represent the same data? In which case we would do:

const { weeklyAlertLevel } = reef.latestDailyData || reef.collectionData || {};

What do you think?

2021-04-22 00:18 UTC, ericboucher commented on packages/website/src/routes/HomeMap/Map/Popup/index.tsx
> +  const {
Similarly here why not deconstruct


reef.latestDailyData || reef.collectionData ?

2021-04-22 00:20 UTC, ericboucher commented on packages/website/src/routes/HomeMap/Map/index.tsx
> +      minZoom={collection ? 1 : 2}
Is this needed?

2021-04-22 00:22 UTC, ericboucher commented on packages/website/src/routes/HomeMap/Map/index.tsx
> +  defaultLayerName?: "Heat Stress" | "Sea Surface Temperature";
Let's type this a bit more strongly and create a MapLayerName type where they are defined maybe?

2021-04-22 00:28 UTC, ericboucher requested changes
Nice work! Let's spend some time to make it cleaner and a bit more future proof.

2021-04-22 00:46 UTC, ericboucher commented on packages/api/src/collections/collections.service.ts
> +  async findOnePublic(collectionId: number) {
findOne and findOnePublic seem quite duplicative

2021-04-22 00:55 UTC, ericboucher commented on packages/api/src/utils/liveData.ts
> +    !satelliteTemperature ||
This stay on one line as  !satelliteTemperature?.value

2021-04-22 00:59 UTC, ericboucher commented on packages/api/src/utils/time-series.utils.ts
> +import { Metric } from '../time-series/metrics.entity';
In any case, a switch statement is probably not the best way to handle this, no?

2021-04-22 12:59 UTC, Ry-DS reviewed
Looking good! Left a few comments

2021-04-22 12:59 UTC, Ry-DS commented on packages/website/src/routes/Dashboard/Info/index.tsx
> +        padding: "18px 16px",
can we use theme.spacing for most these pixel values?

2021-04-22 12:59 UTC, Ry-DS commented on packages/website/src/routes/Dashboard/Map/index.tsx
> +  const isMobile = useMediaQuery(theme.breakpoints.down(320));
is it normal to have a set value? Would be nice to use the preset values by MUI

2021-04-22 12:59 UTC, Ry-DS commented on packages/website/src/routes/Dashboard/Map/index.tsx
> +    <Box className={classes.root} borderRadius="5px" height="480px" mt="46px">
You could move these styles to the class so they are all in one place.

2021-04-22 12:59 UTC, Ry-DS commented on packages/website/src/routes/Dashboard/Map/index.tsx
> +      [theme.breakpoints.between("md", "md")]: {
theme.breakpoints.only?

2021-04-22 12:59 UTC, Ry-DS commented on packages/website/src/routes/Dashboard/index.tsx
> +        ) : null}
You should be  able to do `(staticMode || user) && <Component/>`

2021-04-22 12:59 UTC, Ry-DS commented on packages/website/src/routes/HomeMap/Map/sofarLayers.tsx
> +  defaultLayerName?: "Heat Stress" | "Sea Surface Temperature";
This is repeated from the HomeMap/Map, maybe consolidate to one common type?

2021-04-22 12:59 UTC, Ry-DS commented on packages/website/src/routes/HomeMap/ReefTable/index.tsx
> +  extended?: boolean;
isExtended? And comment to say what this means. What is being extended?

2021-04-22 12:59 UTC, Ry-DS commented on packages/website/src/routes/HomeMap/ReefTable/tableHead.tsx
> +    ? [
This is repetitive. Can't we have an object which holds commonality between the two, and use lodash's merge to add any modifications to each version?

2021-04-22 12:59 UTC, Ry-DS commented on packages/website/src/store/User/userSlice.ts
> +        collection: collections?.[0]?.id
It seems like lines 127-139 and 87-98 are duplicated. Can we make a function which does this work so it isn't repeated twice?

2021-04-22 13:04 UTC, avalmas-programize commented on packages/api/migration/1618313343743-AddCollectionTable.ts
> +        CONSTRAINT "PK_ad3f485bbc99d875491f44d7c85" PRIMARY KEY ("id")
This is how it is generated from TypeORM.
You are correct a simple Primary key can be declared in-line, however I want to edit the autogenerated migration as little as possible because editing sometimes results in confusing typeORM.

2021-04-22 13:26 UTC, avalmas-programize commented on packages/api/src/collections/collections.service.ts
> +    const mappedReefData = collection.reefs.reduce((obj, reef) => {
As it is a intermediate variable used to construct the final object, I don't any better names other than 'acc'

2021-04-22 13:27 UTC, avalmas-programize commented on packages/api/src/collections/dto/filter-public-collcetion.dto.ts
> +import { IsNumber, IsOptional, IsString, Validate } from 'class-validator';
Fixed

2021-04-22 13:27 UTC, avalmas-programize commented on packages/api/src/utils/time-series.utils.ts
> +import { Metric } from '../time-series/metrics.entity';
Deleted, didn't know that lodash provides a camelCase function

2021-04-22 13:33 UTC, avalmas-programize commented on packages/api/src/collections/collections.service.ts
> +  async findOnePublic(collectionId: number) {
Hmm, yeah you are right, fixed

2021-04-22 13:34 UTC, avalmas-programize commented on packages/api/src/utils/liveData.ts
> +    !satelliteTemperature ||
Fixed

2021-04-22 13:41 UTC, avalmas-programize commented on packages/api/src/collections/collections.service.ts
> +        mappedLatestDailyData[reef.id].sst !== undefined
falsey check will fail on `0`, this might cause some really annoying bugs

2021-04-22 13:52 UTC, avalmas-programize commented on packages/api/src/collections/collections.service.ts
> +    }, {}) as Record<number, CollectionData>;
Fixed

2021-04-22 13:53 UTC, avalmas-programize commented on packages/api/src/utils/time-series.utils.ts
> +export const metricToKey = (metric: Metric) => {
I didn't know that such a function existed.
I am a happier man now.

2021-04-22 13:55 UTC, avalmas-programize commented on packages/website/src/routes/HomeMap/Map/Markers/index.tsx
> +            const { weeklyAlert } = reef.collectionData || {};
This was my bad, I shouldn't have altered the name of the variable.
Fixed

2021-04-22 14:01 UTC, tleraj commented on packages/website/src/routes/HomeMap/Map/Markers/index.tsx
> +        disableClusteringAtZoom={collection ? 1 : 2}
We're not using it. Maybe I can disable it at all by setting `disableClusteringAtZoom={1}`?

2021-04-22 14:04 UTC, tleraj commented on packages/website/src/routes/HomeMap/Map/index.tsx
> +      minZoom={collection ? 1 : 2}
On the dashboard page, the map box is smaller than the one in the homepage. There is a case that the collection's site are very far apart, and if we want to display all of them, we should have a zoom level of 1 (the minimum). So in the dashboard page (i.e. `collection` is not falsy) we should let the `minZoon={1}`.

2021-04-22 16:05 UTC, tleraj commented on packages/website/src/common/Delayed/index.tsx
> +const Delayed = ({ children, waitBeforeShow = 500 }: DelayedProps) => {
Or maybe ?

```typescript
type DelayedProps = {
  waitBeforeShow?: number;
};

const Delayed = ({
  children,
  waitBeforeShow = 500,
}: PropsWithChildren<DelayedProps>) => {
  ...
}
```

2021-04-22 16:13 UTC, tleraj commented on packages/website/src/common/Message/index.tsx
> +const Message = ({ message }: MessageProps) => {
I put it in the common folder because it's a common case to display whole screen messages like the one below:

![Screenshot_20210422_191204](https://user-images.githubusercontent.com/64922890/115748345-bf070280-a39e-11eb-9434-2a148493d194.png)

Maybe rename it to `ScreenMessage`?

2021-04-22 16:16 UTC, tleraj commented on packages/website/src/common/NavBar/index.tsx
> +                      {/* TODO: Add dashboard button */}
Will be added [here](https://github.com/aqualinkorg/aqualink-app/pull/534) :wink:

2021-04-22 17:29 UTC, tleraj commented on packages/website/src/common/NavBar/index.tsx
> +  Link as MuiLink,
In https://github.com/aqualinkorg/aqualink-app/pull/534 we are going to add the dashboard button in the user dropdown menu, that's why I've used this rename :wink:

2021-04-22 17:49 UTC, ericboucher commented on packages/api/src/collections/collections.service.ts
> +        mappedLatestDailyData[reef.id].sst !== undefined
still optional chaining would be useful here

2021-04-23 09:31 UTC, Ry-DS commented on packages/api/migration/1618313343743-AddCollectionTable.ts
> +        CONSTRAINT "PK_ad3f485bbc99d875491f44d7c85" PRIMARY KEY ("id")
ahh got it, all good then

2021-04-23 09:33 UTC, Ry-DS commented on packages/website/src/common/Delayed/index.tsx
> +const Delayed = ({ children, waitBeforeShow = 500 }: DelayedProps) => {
I prefer `FC<>` cause its a little stronger and specifies exactly what a component is, but we could use `PropsWithChildren` aswell :+1:

2021-04-23 09:33 UTC, Ry-DS commented on packages/website/src/common/Message/index.tsx
> +const Message = ({ message }: MessageProps) => {
ahh I see. Maybe `FullScreenMessage`?

2021-04-26 04:25 UTC, ericboucher commented on packages/website/src/routes/HomeMap/Map/index.tsx
> +      minZoom={collection ? 1 : 2}
And do we need the "2" in the homepage? Maybe we can have "1" everywhere?

2021-04-26 10:28 UTC, tleraj commented on packages/website/src/routes/Dashboard/BackButton/index.tsx
> +        {/* TODO: Add collection name edit functionality */}
Will be done in https://github.com/aqualinkorg/aqualink-app/pull/534 :wink:

2021-04-26 12:49 UTC, tleraj commented on packages/website/src/routes/Dashboard/index.tsx
> +        ) : null}
Refactored :wink:

2021-04-26 13:30 UTC, tleraj commented on packages/website/src/routes/HomeMap/ReefTable/tableHead.tsx
> +    ? [
I added an extra `display` field to each cell, which is `true` for the standard columns and depends on the `isExtended` prop for the other columns

2021-04-26 14:53 UTC, tleraj commented on packages/website/src/routes/Dashboard/Info/Header.tsx
> +      color: "#AAB1B4",
MUI offers a very specific variety of grey colors

![Screenshot_20210426_173641](https://user-images.githubusercontent.com/64922890/116100845-fb47a500-a6b5-11eb-975e-9af35ad79877.png)

The [figma design](https://www.figma.com/file/Cv9K77K5TWqf2XPdAFeM10/Aqualink-Designs?node-id=0%3A2496) suggests that we should use `#AAB1B4`, which is not offered by MUI. Are you suggesting that we should override MUI's grey color configuration?

2021-04-26 20:36 UTC, merged