Improve map page performance
aqualinkorg/aqualink-app pull request #601
Opened 2021-07-12 14:52 UTC by tleraj

The purpose of this PR is to close https://github.com/aqualinkorg/aqualink-app/issues/569 and https://github.com/aqualinkorg/aqualink-app/issues/599.

Improvements:
 - [x] Use `to` instead of `href` on side menu buttons
 - [x] Make reefs list request on map page only when `!reefsList`
 - [x] Make selected reef request for card only when `reefOnMap.id !== selectedReefId` (useful when going back to the map from the reef details page).
 - [x] Delete ocean sense data once we leave the reef details page

To be done:
 - [ ] Investigate table not scrolling issue when coming to `/map` from `reefs/:reefId`.

2021-07-20 05:30 UTC, Ry-DS reviewed
Overall looks great! Small comments, let me know what you think :)

2021-07-20 05:30 UTC, Ry-DS commented on packages/website/src/common/MenuDrawer/index.tsx
>          color: "#000000",
not related, but can't this just be `'black'`?

2021-07-20 05:30 UTC, Ry-DS commented on packages/website/src/common/MenuDrawer/index.tsx
>          color: "#000000",
Would appreciate if the other colour in this file is also either coming from the theme, or defined as a const with a name so we know what colour it is without opening a colour picker ;)

2021-07-20 05:30 UTC, Ry-DS commented on packages/website/src/routes/HomeMap/ReefTable/body.tsx
> +
this is only used once, and very simple, therefore imo its better to just copy this into the useEffect and delete this callback. What do you think?

2021-07-20 05:30 UTC, Ry-DS commented on packages/website/src/routes/HomeMap/index.tsx
> +    if (!reefOnMap && initialReefId && `${reefOnCardId}` !== initialReefId) {
do we need this template string check? Not too sure what you're trying to do here. Are we trying to avoid a case where they're both undefined?

2021-07-20 09:28 UTC, tleraj commented on packages/website/src/routes/HomeMap/ReefTable/body.tsx
> +
I just wanted the `useEffect` to look cleaner, but yeah that also works :slightly_smiling_face:

2021-07-20 09:35 UTC, tleraj commented on packages/website/src/routes/HomeMap/index.tsx
> +    if (!reefOnMap && initialReefId && `${reefOnCardId}` !== initialReefId) {
Added some explanatory comments :wink:

2021-07-23 13:07 UTC, ericboucher commented
It looks good overall but I deployed on programize and the map tooltip is blinking at the very end after the focusing is finished. Can you check why this happens @tleraj ? It is not happening on prod.

2021-07-23 13:07 UTC, ericboucher requested changes
Let's try and get rid of the "blink" after focus.

2021-07-27 15:24 UTC, ericboucher approved these changes

2021-07-27 17:43 UTC, merged