Robust parameter generation & URL date selector for Sites
aqualinkorg/aqualink-app pull request #642
Opened 2021-12-14 17:07 UTC by tleraj

The purpose of this PR is to close
 - [ ] https://github.com/aqualinkorg/aqualink-app/issues/637
 - [ ] https://github.com/aqualinkorg/aqualink-app/issues/640

2021-12-15 16:38 UTC, ericboucher commented on packages/api/src/utils/time-series.utils.ts
> +  const endDate = end && !isNaN(end.getTime()) ? end : new Date();
add a comment

2021-12-16 15:11 UTC, tleraj commented on packages/api/src/utils/time-series.utils.ts
> +  const endDate = end && !isNaN(end.getTime()) ? end : new Date();
Added this logic into a util function in https://github.com/aqualinkorg/aqualink-app/pull/642/commits/81af6a46eea5e4c021d9438435d39a925486f3a0 :wink:

2021-12-16 16:17 UTC, ericboucher commented on packages/website/src/helpers/siteUtils.ts
> +};
Is there no library that takes a url and an object to return the url with query params? we're not going to do this for every api endpoint...

2021-12-16 16:20 UTC, ericboucher requested changes
Looks good overall, just one main comment around query generation

2021-12-16 16:27 UTC, ericboucher commented on packages/website/src/helpers/siteUtils.ts
> +};
Eg. https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

2021-12-16 16:29 UTC, ericboucher commented on packages/website/src/helpers/siteUtils.ts
> +};
Or other options listed in https://stackoverflow.com/questions/111529/how-to-create-query-parameters-in-javascript

2021-12-17 13:27 UTC, tleraj commented on packages/website/src/helpers/siteUtils.ts
> +};
Using `URLSearchParams` as of https://github.com/aqualinkorg/aqualink-app/pull/642/commits/713a4f6edb8a28bae15b631bb2e9697e7e225b6f

2021-12-17 13:28 UTC, tleraj commented on packages/website/src/helpers/siteUtils.ts
> +export const longDHW = (dhw: number | null): string =>
Adding the `constructTimeSeriesDataRequestUrl` util into `packages/website/src/helpers/siteUtils.ts` caused a dependency cycle. That's why I moved this here

2021-12-17 13:36 UTC, ericboucher commented on packages/website/src/helpers/siteUtils.ts
> +    ...omitBy(rest, isUndefined),
Let's create a util function like that that we can reuse:

`constructQueryParameters`:

```
const params = new URLSearchParams({
    ...omitBy(rest, isUndefined),
    }).toString();

return params.length ? `?${params}` : "";
```

2021-12-17 13:37 UTC, ericboucher approved these changes

2021-12-17 15:09 UTC, merged