Surveys
aqualinkorg/aqualink-app pull request #69
Opened 2020-08-13 17:09 UTC by tleraj

This PR concerns the surveys UI functionality. The designs implemented look like this:
![survey-1](https://user-images.githubusercontent.com/64922890/90164932-a9b5ef00-dda0-11ea-8447-5cc072b227dc.png)
![survey-2](https://user-images.githubusercontent.com/64922890/90164912-a3277780-dda0-11ea-8a4a-5829baf79b18.png)

2020-08-26 00:47 UTC, ericboucher commented
@apanagopoulou-programize make sure that your tests and linter are passing, it is not the case at the moment.

I deployed on staging here - https://aqualink-app-staging.web.app

2020-08-26 17:31 UTC, ericboucher commented
Box disappears on hover:

<img width="356" alt="Screen Shot 2020-08-25 at 4 58 09 PM" src="https://user-images.githubusercontent.com/16843267/91336792-502dc700-e787-11ea-8b2e-e6dd91e25a51.png">

2020-09-03 12:46 UTC, mamadOuologuem commented on packages/website/src/routes/ReefRoutes/Reef/Sensor/index.tsx
> +          <Grid container justify="flex-start" alignItems="center">
The default value of `justify` is `flex-start`

2020-09-03 12:46 UTC, mamadOuologuem commented on packages/website/src/routes/ReefRoutes/Reef/Surveys/Timeline/__snapshots__/index.test.tsx.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
We can have a better test for `Timeline`?

2020-09-03 12:46 UTC, mamadOuologuem commented on packages/website/src/routes/ReefRoutes/Reef/Surveys/Timeline/index.tsx
> +                <Grid container item xs={12}>
There shouldn't be an `item` here

We can't have a <Grid item> which isn't contained in a <Grid container>

2020-09-03 12:46 UTC, mamadOuologuem commented on packages/website/src/routes/ReefRoutes/Reef/Surveys/Timeline/index.tsx
> +                            image={survey.featuredSurveyMedia?.url}
We just tested above that `survey.featuredSurveyMedia` is not null so we can simply use `survey.featuredSurveyMedia.url`

2020-09-03 12:46 UTC, mamadOuologuem commented on packages/website/src/routes/ReefRoutes/Reef/Surveys/TimelineMobile/index.tsx
> +const styles = (theme: Theme) =>
Looks like `....../Reef/Surveys/TimelineMobile/index.tsx` and `....../Reef/Surveys/Timeline/index.tsx` are sharing a lot in common.
I think we can dry that a bit.

The most important part is the styles. 
For eg. in classses.cardValues or classes.cardFields we are defining colors (color: "2fxx2xf") in both files. We will have to edit the two files if we want to change the color of the cards' values or fields.

This example can be applied to other CSS properties and component code

2020-09-03 12:46 UTC, mamadOuologuem commented on packages/website/src/services/surveyServices.ts
> +    url: `surveys`,
```suggestion
    url: "surveys",
```

2020-09-03 12:46 UTC, mamadOuologuem commented on packages/website/src/routes/Surveys/index.tsx
> +            justify="flex-start"
```suggestion
```

2020-09-03 12:46 UTC, mamadOuologuem commented on packages/website/src/routes/Surveys/View/index.tsx
> +                    // TODO - Remove default
👣 ?

2020-09-03 12:46 UTC, mamadOuologuem commented on packages/website/src/routes/Surveys/View/SurveyMediaDetails.tsx
> +          <div key={index}>
```suggestion
          <div key={point.name}>
```

2020-09-03 12:46 UTC, mamadOuologuem commented on packages/website/src/routes/Surveys/View/Charts/index.tsx
> +            </>
```suggestion
            <Tooltip {...tooltipData} />
            <div className="tooltip-arrow" />
```

2020-09-03 12:46 UTC, mamadOuologuem commented on packages/website/src/routes/Surveys/View/Charts/index.tsx
> +            }}
Worth using `className={classes.mtTooltip}`

This kind of inline styling can lead to design breaks on other browser depending on their interpretation

2020-09-03 12:46 UTC, mamadOuologuem commented on packages/website/src/routes/Surveys/View/Charts/index.tsx
> +    setTimeout(() => {
A comment to explain why `setTimeout`?

2020-09-07 09:54 UTC, ericboucher commented on packages/website/src/store/Survey/types.ts
> +  type: string;
observations and type should be more strongly typed. We know exactly what values they can take

2020-09-07 09:55 UTC, ericboucher commented on packages/website/src/store/Survey/types.ts
> +  temperature?: string;
Shouldn't this be a number?

2020-09-07 09:56 UTC, ericboucher requested changes

2020-09-07 09:56 UTC, ericboucher commented on packages/website/src/store/Survey/types.ts
> +  weatherConditions: string;
Same, this should be more strongly typed, we know what values it can take

2020-09-07 09:56 UTC, ericboucher commented on packages/website/src/store/Survey/types.ts
> +  observations: string;
Add stronger type

2020-09-09 16:36 UTC, tleraj commented on packages/website/src/layout/App/App.css
> +}
Fixed on https://github.com/aqualinkorg/aqualink-app/pull/157 by https://github.com/aqualinkorg/aqualink-app/pull/157/commits/8489eca13b1f3cbba6f71104a92a331499b3e3f3.

2020-09-10 09:17 UTC, tleraj commented on packages/website/src/routes/Surveys/View/Charts/index.tsx
> +            }}
I totally agree. However, I didn't find a way to pass the variables `tooltipPosition.top` and `tooltipPosition.left` to the `createStyles` method. Any suggestions?

2020-09-10 09:20 UTC, tleraj commented on packages/website/src/routes/Homepage/RegisterDialog/index.tsx
> +            <Grid style={{ marginTop: "0.5rem" }} container item xs={10}>
Fix on https://github.com/aqualinkorg/aqualink-app/pull/157 by https://github.com/aqualinkorg/aqualink-app/pull/157/commits/61241921b5b97e18d9316fb2e58f1a1d97685d30.

2020-09-10 09:20 UTC, tleraj commented on packages/website/src/routes/Homepage/RegisterDialog/index.tsx
> +                      </Link>
Didn't work. However, I removed inline styles in https://github.com/aqualinkorg/aqualink-app/pull/157/commits/61241921b5b97e18d9316fb2e58f1a1d97685d30

2020-09-10 09:48 UTC, tleraj commented on packages/website/src/routes/ReefRoutes/Reef/Surveys/Timeline/__snapshots__/index.test.tsx.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
Fixed on https://github.com/aqualinkorg/aqualink-app/pull/157 by https://github.com/aqualinkorg/aqualink-app/pull/157/commits/8d09c3a9c8943f2e70d3ba128d719675b890420e

2020-09-10 09:55 UTC, tleraj commented on packages/website/src/routes/ReefRoutes/Reef/Surveys/Timeline/index.tsx
> +                <Grid container item xs={12}>
Didn't fully catch that, but I think I fixed it on https://github.com/aqualinkorg/aqualink-app/pull/157 by https://github.com/aqualinkorg/aqualink-app/pull/157/commits/80d354985bfeef808ee6786658f247ae5025b0da.

2020-09-10 10:42 UTC, tleraj commented on packages/website/src/routes/ReefRoutes/Reef/Surveys/TimelineMobile/index.tsx
> +const styles = (theme: Theme) =>
Created common styles for this two components. Check https://github.com/aqualinkorg/aqualink-app/pull/157/commits/5dc9535b85108323287c46d32e9031119f7e5ec1.

2020-09-10 11:01 UTC, tleraj commented on packages/website/src/routes/Surveys/View/Charts/index.tsx
> +    setTimeout(() => {
Check https://github.com/aqualinkorg/aqualink-app/pull/157/commits/8aedaee3ce9a1f951a54fb6d82211375c67278ef.

2020-09-10 12:12 UTC, tleraj commented on packages/website/src/store/Survey/types.ts
> +  type: string;
Fixed by https://github.com/aqualinkorg/aqualink-app/pull/157/commits/e9bb2fedd1303d406644eef4182823e0334c0cbc.

2020-09-10 12:13 UTC, tleraj commented on packages/website/src/store/Survey/types.ts
> +  temperature?: string;
Fixed by https://github.com/aqualinkorg/aqualink-app/pull/157/commits/e9bb2fedd1303d406644eef4182823e0334c0cbc.

2020-09-10 15:17 UTC, tleraj commented on packages/website/src/store/Survey/types.ts
> +  weatherConditions: string;
Fixed by https://github.com/aqualinkorg/aqualink-app/pull/157/commits/ab4aab6cb36d164a67d7b039047343cfa8d7d573

2020-09-11 10:26 UTC, closed without merging