Add delete button to the data upload table
aqualinkorg/aqualink-app pull request #702
Opened 2022-04-07 14:10 UTC by echaidemenos

The purpose of this PR is to close [#693](https://github.com/aqualinkorg/aqualink-app/issues/693)

2022-04-08 15:13 UTC, ericboucher commented on packages/api/src/utils/uploads/upload-sheet-data.ts
> +    if (surveyPoint && uploadExists) {
no need to test for surveyPoint here since it is part of the query above.

2022-04-08 15:15 UTC, ericboucher commented on packages/website/src/routes/SiteRoutes/UploadData/HistoryTable.tsx
> +                    "aria-label": "select all desserts",
👣

2022-04-08 15:16 UTC, ericboucher commented on packages/website/src/routes/SiteRoutes/UploadData/HistoryTable.tsx
> +              }
This whole part of the file could be largely simplified

2022-04-08 15:20 UTC, ericboucher requested changes
@echaidemenos nice work. In terms of flow, I think it is safer to add the delete button on each row on the very right side. You can re-use the styled icon from the delete survey buttons.

<img width="925" alt="Screen Shot 2022-04-08 at 11 18 17 AM" src="https://user-images.githubusercontent.com/16843267/162472246-b3abe30d-acb0-4620-9d5b-d4306957d728.png">

And add a confirmation message when people click on delete. You can re-use the confirmation popup used for "Exclusion Dates"

<img width="796" alt="Screen Shot 2022-04-08 at 11 19 35 AM" src="https://user-images.githubusercontent.com/16843267/162472499-2b5599da-f660-4f52-9578-7316565b7619.png">

2022-04-12 14:11 UTC, echaidemenos commented
@ericboucher i used `DeleteDialog` instead of `ConfirmationDialog`, since it was already used by delete button on survey cards. I also made this button reusable 

![Screenshot from 2022-04-12 16-58-47](https://user-images.githubusercontent.com/80451946/162981202-3e308532-e13e-42a2-9625-20f838b1e7f6.png)

![Screenshot from 2022-04-12 16-58-54](https://user-images.githubusercontent.com/80451946/162981254-3d6d35aa-e00a-4058-8bb6-92781371af7e.png)

2022-04-12 19:11 UTC, ericboucher approved these changes

2022-04-13 00:16 UTC, ericboucher commented
@echaidemenos the date range looks cramped for me. Let's update the styling so that the date range fits on one line

<img width="425" alt="Screen Shot 2022-04-12 at 8 13 37 PM" src="https://user-images.githubusercontent.com/16843267/163074860-b7ed1bdc-1fd1-4fa3-ad35-9fe8ea211c26.png">

2022-04-14 09:34 UTC, echaidemenos commented
> @echaidemenos the date range looks cramped for me. Let's update the styling so that the date range fits on one line. As a first step you can reduce the spacing around the delete icon.
> 
> <img alt="Screen Shot 2022-04-12 at 8 13 37 PM" width="425" src="https://user-images.githubusercontent.com/16843267/163074860-b7ed1bdc-1fd1-4fa3-ad35-9fe8ea211c26.png">
@ericboucher i can't reproduce this. i have used midori, safari, chrome, firefox and a lot of different window sizes and dates. Under which conditions this happens?

2022-04-14 15:05 UTC, echaidemenos commented
> t

ok fixed it. spacing wouldn't work. i added just `whiteSpace: "nowrap"`

2022-04-14 16:33 UTC, ericboucher approved these changes

2022-04-14 21:50 UTC, merged