Issue 744/add 3d model
aqualinkorg/aqualink-app pull request #747
Opened 2022-06-01 10:45 UTC by PysarenkoDS-BWT

Add migration with new table
Add new module to backend
Add new siteService `getSiteSketchFab`
Add viewer for `SketchFab`

2022-06-01 12:23 UTC, ericboucher commented on packages/api/src/site-sketch-fab/site-sketch-fab.entity.ts
> +  @ApiProperty({ example: 'Some description' })
update description

2022-06-01 12:26 UTC, ericboucher commented on packages/api/src/site-sketch-fab/site-sketch-fab.module.ts
> +  imports: [TypeOrmModule.forFeature([SiteSketchFab])],
small thing but let's call it `sketchfab` in one word

2022-06-02 08:14 UTC, echaidemenos commented on packages/api/src/site-sketch-fab/dto/find-sketch-fab.dto.ts
> +  siteId: number;
consider adding this bit of validation also `@Validate(EntityExists, [Site])`. Like we do in other dtos, for example in `create-survey-point.dto.ts`

2022-06-02 08:26 UTC, echaidemenos requested changes

2022-06-02 08:26 UTC, echaidemenos commented on packages/api/src/site-sketch-fab/site-sketch-fab.controller.ts
> +@Controller('site-sketch-fab')
It would be nice to use, here and where we can, `@ApiTags('...')`. https://docs.nestjs.com/openapi/operations

2022-06-02 08:26 UTC, echaidemenos commented on packages/api/src/site-sketch-fab/dto/find-sketch-fab.dto.ts
> +  siteId: number;
consider adding this bit of validation also `@Validate(EntityExists, [Site])`. Like we do in other dtos, for example in `create-survey-point.dto.ts`

2022-06-02 11:48 UTC, echaidemenos approved these changes

2022-06-03 12:48 UTC, echaidemenos commented on packages/api/src/utils/sofar-availability.ts
> +    // eslint-disable-next-line fp/no-mutation
since `getSofarWaveModelAvailability` only inits ans returns `geojson`, cant we just do this?
```
const geojson: FeatureCollection<Point> = {
  type: 'FeatureCollection',
  features: availabilityPoints.map((coordinate) => ({
    type: 'Feature',
    geometry: {
      type: 'Point',
      coordinates: coordinate,
    },
  })),
};
```

2022-06-03 13:39 UTC, PysarenkoDS-BWT commented on packages/api/src/utils/sofar-availability.ts
> +    // eslint-disable-next-line fp/no-mutation
I'm not created this, I don't know why we need this function.
Personally, I would create this variable once

2022-06-03 13:40 UTC, PysarenkoDS-BWT commented on packages/api/src/utils/sofar-availability.ts
> +    // eslint-disable-next-line fp/no-mutation
I'm only add comment to successfully pass test

2022-06-05 10:20 UTC, merged