Create resized survey images
aqualinkorg/aqualink-app pull request #764
Opened 2022-06-15 11:22 UTC by echaidemenos

The purpose of this PR is to resolve https://github.com/aqualinkorg/aqualink-app/issues/691

This PR:
- Adds a script that gets all image urls from `survey_media` table and uploads new resized versions. Example usage `yarn resize-survey-images -s 512`. The resized images urls would be in the form of `https://storage.googleapis.com/reef_media_programize/be-dev/surveys/site-image-24cc936cc50ce8c8.jpg=s512`
- Makes uploading a survey picture saves it's resized version. The width must be set with `SURVEY_IMAGE_RESIZE` env variable.
- `/site/:siteId` route requests first for resized survey pictures, if they exists, to reduce loading time. `/sites/:siteId/survey_details/:surveyId` shows the original media.

2022-06-16 10:32 UTC, ericboucher commented on packages/api/src/surveys/surveys.service.ts
> +  private readonly SURVEY_IMAGE_RESIZE = Number(
Also, what happens if the uploaded image is smaller than our thumbnail size?

2022-06-16 10:34 UTC, ericboucher commented on packages/website/src/common/SiteDetails/Surveys/SurveyCard/index.tsx
> +                      ? `${survey.featuredSurveyMedia?.url}=s${REDUCED_IMAGE_SIZE}`
this should not happen here. The api could return "url" and "thumbnailUrl", which you could use in the frontend.

The frontend should not need to know anything about the reduced_image_size

2022-06-17 09:46 UTC, echaidemenos commented on packages/api/src/surveys/surveys.service.ts
> +  private readonly SURVEY_IMAGE_RESIZE = Number(
> Also, what happens if the uploaded image is smaller than our thumbnail size?

we check if image is smaller before resizing and uploading. So in some cases the original image will be kept only

2022-06-17 13:31 UTC, ericboucher commented on packages/api/src/surveys/surveys.service.ts
> +  private readonly surveyImageResizeWidth = 512;
Maybe add a comment above to explain what this number is used for?

2022-06-17 13:34 UTC, ericboucher commented on packages/website/src/common/SiteDetails/FeaturedMedia/index.tsx
> +          onError={(e: any) => {
This still does not feel right. I think the backend should be the one sending the thumbnail link when it exists, so the survey object should return both the imageUrl and thumbnailUrl (when it exists).

2022-06-17 13:35 UTC, ericboucher commented on packages/website/src/routes/HomeMap/SiteTable/SelectedSiteCard/__snapshots__/index.test.tsx.snap
> +        Featured Site
why did this change happen?

2022-06-17 13:35 UTC, ericboucher commented on packages/website/src/common/SiteDetails/FeaturedMedia/index.tsx
> +          onError={(e: any) => {
So the frontend should just need to do:

- thumbnailUrl || imageUrl 

-> no need for error handling
-> no need for `getThumbnailLink`

2022-06-17 13:36 UTC, ericboucher requested changes
Better. But following up on my previous comments, the frontend should not be required to know the formatting for a thumbnail url. This url should ideally be returned dircetly by the API

2022-06-17 13:57 UTC, echaidemenos commented on packages/website/src/routes/HomeMap/SiteTable/SelectedSiteCard/__snapshots__/index.test.tsx.snap
> +        Featured Site
a change in my .env caused this. I will bring it back

2022-06-17 13:58 UTC, ericboucher commented on packages/website/src/utils/helpers.tsx
> +  // eslint-disable-next-line fp/no-mutation
Agreed. Though I think we should delete this function completely @echaidemenos ;)

2022-06-21 10:12 UTC, echaidemenos commented on packages/website/src/utils/helpers.tsx
> +  // eslint-disable-next-line fp/no-mutation
thanks for the tip, i will change to this in places i use similar login, because this function will be removed

2022-06-23 20:43 UTC, ericboucher commented on packages/api/migration/1655476789970-AddThumbnailUrlToSurveyMedia.ts
> +      `ALTER TABLE "survey_media" RENAME COLUMN "url" TO "original_url"`,
Maybe we can keep url, and simply add the thumbnail_url, wdyt?

2022-06-23 20:48 UTC, ericboucher commented on packages/api/scripts/resize-survey-images.ts
> +    const destination = modified.join('/');
let's do this in one line

2022-06-23 20:51 UTC, ericboucher commented on packages/api/src/surveys/surveys.service.ts
> +    const destination = modified.join('/');
a lot of this seems duplicative of what's in the upload script file, maybe you could extract this as a utility function?

2022-06-23 20:57 UTC, ericboucher approved these changes
Great work @echaidemenos 

- Let's switch back to "url" instead of "originalUrl"
- Let's dedup the code a bit between the script and the service file

2022-06-24 10:15 UTC, ericboucher approved these changes

2022-06-24 10:16 UTC, merged